const schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "DockButtonSchema",
  "title": "DockButton (Any)",
  "description": "Schema que descreve qualquer tipo de DockButton.",
  "type": "object",
  "oneOf": [
    { "$ref": "#/definitions/DockButtonAppsByTag" },
    { "$ref": "#/definitions/DockButtonApp" },
    { "$ref": "#/definitions/DockButtonAction" },
    { "$ref": "#/definitions/DockButtonDropdown" }
  ],
  "definitions": {
    "DockButtonBase": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The id for the dock entry. This will be generated by the backend."
        },
        "visible": {
          "type": "boolean",
          "description": "Is the dock entry visible."
        },
        "tooltip": {
          "type": "string",
          "description": "The tooltip to be shown for this button/entry."
        },
        "iconUrl": {
          "type": "string",
          "description": "The icon to use to distinguish this entry from others."
        },
        "conditions": {
          "type": "array",
          "items": { "type": "string" },
          "description": "Condition to determine if the item should be shown."
        },
        "owner": {
          "type": "string",
          "description": "The owner of the dock button."
        },
        "name": {
          "type": "string",
          "description": "The name of the dock button."
        }
      },
      "required": ["owner", "name"]
    },
    "DockButtonAppsByTag": {
      "allOf": [
        { "$ref": "#/definitions/DockButtonBase" },
        {
          "type": "object",
          "properties": {
            "type": {
              "const": "DockButtonAppsByTag"
            },
            "display": {
              "type": "string",
              "enum": ["individual", "group"],
              "description": "Should this entry show a single app or a group of apps."
            },
            "tags": {
              "type": "array",
              "items": { "type": "string" },
              "description": "The tags to use to find the single app or collection of apps."
            },
            "noEntries": {
              "type": "string",
              "description": "Text to display if there are no tagged apps."
            }
          },
          "required": ["type", "display"]
        }
      ]
    },
    "DockButtonApp": {
      "allOf": [
        { "$ref": "#/definitions/DockButtonBase" },
        {
          "type": "object",
          "properties": {
            "type": {
              "const": "DockButtonApp"
            },
            "appId": {
              "type": "string",
              "description": "Launch an app by its id."
            }
          },
          "required": ["type", "appId"]
        }
      ]
    },
    "DockButtonAction": {
      "allOf": [
        { "$ref": "#/definitions/DockButtonBase" },
        {
          "type": "object",
          "properties": {
            "type": {
              "const": "DockButtonAction"
            },
            "action": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "The id of the action to fire."
                },
                "customData": {
                  "description": "Data that should be passed to the action (any type)."
                }
              },
              "required": ["id"]
            }
          },
          "required": ["type", "action"]
        }
      ]
    },
    "DockButtonDropdown": {
      "allOf": [
        { "$ref": "#/definitions/DockButtonBase" },
        {
          "type": "object",
          "properties": {
            "type": {
              "const": "DockButtonDropdown"
            },
            "options": {
              "type": "array",
              "description": "List of button options",
              "items": {
                "oneOf": [
                  { "$ref": "#/definitions/OmitDockButtonAppsByTagId" },
                  { "$ref": "#/definitions/OmitDockButtonAppId" },
                  { "$ref": "#/definitions/OmitDockButtonActionId" },
                  { "$ref": "#/definitions/OmitDockButtonDropdownId" }
                ]
              }
            },
            "noEntries": {
              "type": "string",
              "description": "Text if there are no entries because conditions excluded everything."
            }
          },
          "required": ["type", "options"]
        }
      ]
    },
    "OmitDockButtonAppsByTagId": {
      "type": "object",
      "description": "DockButtonAppsByTag sem a propriedade 'id'.",
      "properties": {
        "type": {
          "const": "DockButtonAppsByTag"
        },
        "visible": { "type": "boolean" },
        "tooltip": { "type": "string" },
        "iconUrl": { "type": "string" },
        "conditions": {
          "type": "array",
          "items": { "type": "string" }
        },
        "display": {
          "type": "string",
          "enum": ["individual", "group"]
        },
        "tags": {
          "type": "array",
          "items": { "type": "string" }
        },
        "noEntries": { "type": "string" },
        "owner": { "type": "string" },
        "name": { "type": "string" }
      },
      "required": ["type", "display", "owner", "name"]
    },
    "OmitDockButtonAppId": {
      "type": "object",
      "description": "DockButtonApp sem a propriedade 'id'.",
      "properties": {
        "type": {
          "const": "DockButtonApp"
        },
        "visible": { "type": "boolean" },
        "tooltip": { "type": "string" },
        "iconUrl": { "type": "string" },
        "conditions": {
          "type": "array",
          "items": { "type": "string" }
        },
        "appId": { "type": "string" },
        "owner": { "type": "string" },
        "name": { "type": "string" }
      },
      "required": ["type", "appId", "owner", "name"]
    },
    "OmitDockButtonActionId": {
      "type": "object",
      "description": "DockButtonAction sem a propriedade 'id'.",
      "properties": {
        "type": {
          "const": "DockButtonAction"
        },
        "visible": { "type": "boolean" },
        "tooltip": { "type": "string" },
        "iconUrl": { "type": "string" },
        "conditions": {
          "type": "array",
          "items": { "type": "string" }
        },
        "action": {
          "type": "object",
          "properties": {
            "id": { "type": "string" },
            "customData": {}
          },
          "required": ["id"]
        },
        "owner": { "type": "string" },
        "name": { "type": "string" }
      },
      "required": ["type", "action", "owner", "name"]
    },
    "OmitDockButtonDropdownId": {
      "type": "object",
      "description": "DockButtonDropdown sem a propriedade 'id'.",
      "properties": {
        "type": {
          "const": "DockButtonDropdown"
        },
        "visible": { "type": "boolean" },
        "tooltip": { "type": "string" },
        "iconUrl": { "type": "string" },
        "conditions": {
          "type": "array",
          "items": { "type": "string" }
        },
        "options": {
          "type": "array",
          "items": {
            "oneOf": [
              { "$ref": "#/definitions/OmitDockButtonAppsByTagId" },
              { "$ref": "#/definitions/OmitDockButtonAppId" },
              { "$ref": "#/definitions/OmitDockButtonActionId" },
              { "$ref": "#/definitions/OmitDockButtonDropdownId" }
            ]
          }
        },
        "noEntries": { "type": "string" },
        "owner": { "type": "string" },
        "name": { "type": "string" }
      },
      "required": ["type", "options", "owner", "name"]
    }
  }
};

export default schema;

